---
abstract: 'A Task to install all POE simple TCP/IP services modules.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-POE-Simple-TCPIP-Services
no_index:
  directory:
    - inc
    - t
requires:
  POE: 1.0001
  POE::Component::Server::Chargen: 1.1
  POE::Component::Server::Daytime: 1.1
  POE::Component::Server::Discard: 1.1
  POE::Component::Server::Echo: 1.6
  POE::Component::Server::Qotd: 1.1
  POE::Component::Server::Time: 1.1
tests: 't/*.t xt/*.t'
version: 1.08
